package com.zhq.entity;

import java.io.Serializable;

/**
 * 商品详情介绍类
 */
public class ProductDesc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.product_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.p_desc
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String pDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.id
     *
     * @return the value of product_desc.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.id
     *
     * @param id the value for product_desc.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.product_id
     *
     * @return the value of product_desc.product_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.product_id
     *
     * @param productId the value for product_desc.product_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.p_desc
     *
     * @return the value of product_desc.p_desc
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.p_desc
     *
     * @param pDesc the value for product_desc.p_desc
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setpDesc(String pDesc) {
        this.pDesc = pDesc == null ? null : pDesc.trim();
    }
}