package com.zhq.entity;


import java.io.Serializable;
import java.util.Date;

/**
 * 商品信息类
 */
public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prive
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long prive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_price
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_point
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String salePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.image
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.flag
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type_name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prive
     *
     * @return the value of product.prive
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getPrive() {
        return prive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prive
     *
     * @param prive the value for product.prive
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setPrive(Long prive) {
        this.prive = prive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_price
     *
     * @return the value of product.sale_price
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_price
     *
     * @param salePrice the value for product.sale_price
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_point
     *
     * @return the value of product.sale_point
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getSalePoint() {
        return salePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_point
     *
     * @param salePoint the value for product.sale_point
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setSalePoint(String salePoint) {
        this.salePoint = salePoint == null ? null : salePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of product.image
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.flag
     *
     * @return the value of product.flag
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.flag
     *
     * @param flag the value for product.flag
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_user
     *
     * @return the value of product.create_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_user
     *
     * @param createUser the value for product.create_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_user
     *
     * @return the value of product.update_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_user
     *
     * @param updateUser the value for product.update_user
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_id
     *
     * @return the value of product.type_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_id
     *
     * @param typeId the value for product.type_id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type_name
     *
     * @return the value of product.type_name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type_name
     *
     * @param typeName the value for product.type_name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}