package com.zhq.entity;

import java.io.Serializable;

/**
 * 商品类别类
 */
public class ProductType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.pid
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.id
     *
     * @return the value of product_type.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.id
     *
     * @param id the value for product_type.id
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.pid
     *
     * @return the value of product_type.pid
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.pid
     *
     * @param pid the value for product_type.pid
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.name
     *
     * @return the value of product_type.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.name
     *
     * @param name the value for product_type.name
     *
     * @mbggenerated Mon Apr 11 14:36:24 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}