spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.197.130:3306/springboot_dubbo
    username: root
    password: 4213

#dubbo
dubbo:
  application:
    name: product-service
  registry:
    address: zookeeper://192.168.197.130:2181
    check: false
  protocol:
    name: dubbo
    port: 28800

mybatis:
  mapper-locations: classpath:mapper/*.xml  #指定mapper.xml文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制打印sql执行语句日志

server:
  port: 8080

