#dubbo
dubbo:
  application:
    name: item-service #????
  registry:
    address: zookeeper://192.168.197.130:2181
    check: false
  protocol:
    name: dubbo
    port: 28802

server:
  port: 8082

spring:
  #?????
  datasource:
    url: jdbc:mysql://192.168.197.130:3306/springboot_dubbo
    username: root
    password: 4213

  rabbitmq:
    host: 192.168.197.130
    port: 5672
    username: zhq
    password: 4213

mybatis:
  mapper-locations: classpath:mapper/*.xml  #??mapper.xml?????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #????sql??????

html:
  locations: D:\JavaWeb\SpringBoot-Dubbo\
