dubbo:
  application:
    name: first
  registry:
    address: zookeeper://192.168.197.130:2181
    check: false
  consumer:
    timeout: 200000
    check: false
    retries: 0

server:
  port: 9091

spring:
  thymeleaf:
    cache: false



